; PlatformIO IoT Radio for ESP32-S3 N16R8 + MAX98357A
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; N16R8 = 16MB Flash, no PSRAM
board_build.flash_size = 16
board_upload.flash_size = 16MB
board_build.psram_type = null

; Library dependencies
lib_deps =
    earlephilhower/ESP8266Audio@^1.4.4